# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160205_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantitative_Variable',
            new_name='QualitativeVariable',
        ),
        migrations.RenameModel(
            old_name='Qualitative_Variable',
            new_name='QuantitativeVariable',
        ),
    ]
