# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20160205_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakpoint',
            name='color',
        ),
    ]
