# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:20
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_breakpoint_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakpoint',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=10),
        ),
    ]
